import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Flex,
  Grid,
  GridItem,
  Heading,
  Input,
  SimpleGrid,
  Stack,
  Text,
} from "@chakra-ui/react";
import Navbar from "@/components/Navbar";
import Button from "@/components/Button";
import { ArrowForwardIcon } from "@chakra-ui/icons";
import { useEffect, useRef } from "react";
import { motion, useInView } from "framer-motion";
import HomeProjectCmp from "@/components/HomeProjectCmp";
import BlogItemCmp from "@/components/BlogItemCmp";
import ImagesList from "@/images.json";

const CoreValuesObj = [
  {
    title: "FOCUS",
    subtitle:
      "Precision and attention to detail define our approach, ensuring that every project meets the highest standards.",
  },
  {
    title: "SIMPLICITY/SYNERGY",
    subtitle:
      "We simplify complex processes and synergize efforts to deliver exceptional results efficiently.",
  },
  {
    title: "HONESTY",
    subtitle:
      "Our commitment to honesty builds strong, trustworthy relationships with clients and stakeholders.",
  },
  {
    title: "LEADERSHIP",
    subtitle:
      "Our commitment to honesty builds strong, trustworthy relationships with clients and stakeholders.",
  },
];

export default function AboutUs() {
  const navRef = useRef(null);
  const isInView = useInView(navRef, { once: false, amount: 0.6 });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className="section-container">
          <Box
            position={"absolute"}
            top={"40px"}
            w="full"
            left={0}
            px={"100px"}
            mx={"auto"}
            zIndex={2}
          >
            <Navbar />
          </Box>
          <Box
            position={"fixed"}
            top={"40px"}
            w="full"
            left={0}
            px={"100px"}
            mx={"auto"}
            zIndex={2}
          >
            <Box
              display={isInView ? "none" : "block"}
              //   opacity={isInView ? 0 : 1}
              transition={"opacity .5s ease-in-out"}
              bg={"white"}
              boxShadow={"2px 2px 8px 0px rgba(0, 0, 0, 0.08)"}
              p="20px"
              borderRadius={"8px"}
            >
              <Navbar />
            </Box>
          </Box>
        </nav>
        <section ref={navRef}>
          <Box className="section-container" pt={"206px"}>
            <Heading
              color={"primary"}
              fontSize={"72px"}
              fontWeight={700}
              lineHeight={"100%"}
              letterSpacing={"-2.88px"}
            >
              We’re transforming the way the world builds.
            </Heading>
          </Box>
          <Box
            h="444px"
            bg={"gray"}
            bgImage={ImagesList.about.hero}
            mt="62px"
          ></Box>
        </section>
        <section className="section-container">
          <Box pt={"100px"} pb={"108px"}>
            <Box w="55%" maxW={"655px"}>
              <Text
                fontSize={"20px"}
                fontWeight={600}
                letterSpacing={"4px"}
                textTransform={"uppercase"}
                color={"secondary"}
              >
                Company Overview
              </Text>
              <Heading
                color={"primary"}
                fontSize={"56px"}
                fontWeight={700}
                lineHeight={"100%"}
                letterSpacing={"-2.24px"}
                mt={"21px"}
              >
                About First Synergi Homes
              </Heading>
            </Box>
            <Box mt={"37px"}>
              <Text
                color={"primary"}
                fontSize={"20px"}
                fontWeight={400}
                lineHeight={"130%"}
                style={{ columnCount: 2, columnGap: "60px" }}
              >
                First Synergi Homes Limited was Incorporated in 2007, and
                primarily formed to cater to the need for exclusive private home
                development and alluringly built-up living communities.
                <br />
                <br />
                Inspired by real life experiences coupled with the glaring need
                to develop structures that are not just aesthetically pleasing
                to behold but also structurally sound and sustainable for
                decades to come.
                <br />
                <br />
                We are a firm committed to the actualization of the finest
                quality of building design and construction at par with
                international standards, with a lot of emphasis placed on
                quality, practicality, spatial management, smart and energy
                efficiency.
                <br />
                Our work focuses on possibilities that are open to the
                architectural and construction industry, through advancement in
                technology and the constant development of various finishing
                materials. Our properties cutting across the length and breadth
                of the country, each have their own unique design aesthetic,
                providing an aspirational lifestyle within a thriving community.
                <br />
                <br />
                In addition, we also employ a consultative approach in working
                with clients who have specific home dreams and needs they intend
                to bring to reality, either to live in or to have as an
                investment. We are wholeheartedly committed to building enduring
                relationships and providing a plethora of expertise and
                solutions to meet our client&apos;s ever-evolving needs.
              </Text>
            </Box>
          </Box>
        </section>
        <section>
          <Box h="667px" w="full" bgImage={"/skyscraper_bg.png"} mt="62px">
            <Flex
              direction={"column"}
              justify={"center"}
              className="section-container"
              h={"100%"}
            >
              <Heading
                fontSize={"56px"}
                lineHeight={"120%"}
                letterSpacing={"-2.24px"}
                color={"white"}
                textAlign={"center"}
              >
                For those who seek an Exceptional Home and a<br /> Lifestyle of
                Opulence,
                <br /> WELCOME on this journey with us
              </Heading>
              <Flex mt={"57px"} gap={"50px"} color={"white"}>
                <Box w="50%">
                  <Text
                    fontSize={"20px"}
                    fontWeight={600}
                    letterSpacing={"4px"}
                    textTransform={"uppercase"}
                    color={"secondary"}
                  >
                    Our Vision
                  </Text>
                  <Text
                    fontSize={"20px"}
                    fontWeight={400}
                    lineHeight={"130%"}
                    mt="21px"
                  >
                    To be the most sought after Property Development Company for
                    everyone who dreams to own a Home.
                  </Text>
                </Box>
                <Box w="50%">
                  <Text
                    fontSize={"20px"}
                    fontWeight={600}
                    letterSpacing={"4px"}
                    textTransform={"uppercase"}
                    color={"secondary"}
                  >
                    Our Vision
                  </Text>
                  <Text
                    fontSize={"20px"}
                    fontWeight={400}
                    lineHeight={"130%"}
                    mt="21px"
                  >
                    To be the most sought after Property Development Company for
                    everyone who dreams to own a Home.
                  </Text>
                </Box>
              </Flex>
            </Flex>
          </Box>
        </section>
        <section className="section-container">
          <Flex mt={"77px"} gap={"38px"} position={"relative"}>
            <Box w="65%">
              <Text
                color={"secondary"}
                fontSize={"20px"}
                lineHeight={"130%"}
                letterSpacing={"4px"}
                textTransform={"capitalize"}
              >
                How we stand for
              </Text>
              <Heading color={"primary"} mt={"21px"} fontSize={"56px"}>
                Core Values
              </Heading>
              <SimpleGrid
                columns={2}
                gridGap={"50px"}
                minChildWidth={"280px"}
                mt={"34px"}
              >
                {CoreValuesObj.map((obj, index) => (
                  <Box key={index} maxW={"302px"}>
                    <Text
                      color={"secondary"}
                      fontSize={"20px"}
                      lineHeight={"130%"}
                      letterSpacing={"4px"}
                      textTransform={"capitalize"}
                    >
                      {obj.title}
                    </Text>
                    <Text
                      color={"primary"}
                      fontSize={"20px"}
                      lineHeight={"130%"}
                    >
                      {obj.subtitle}
                    </Text>
                  </Box>
                ))}
              </SimpleGrid>
            </Box>
            <Box>
              <Image
                src={ImagesList.about.section3}
                alt="project-image"
                width={649}
                height={597}
              />
            </Box>
          </Flex>
        </section>
        <section className="section-container">
          <Box my={"100px"}>
            <Text
              color={"secondary"}
              fontSize={"20px"}
              lineHeight={"130%"}
              letterSpacing={"4px"}
              textTransform={"capitalize"}
            >
              OUR SERVICES
            </Text>
            <Heading color={"primary"} mt={"21px"} fontSize={"56px"}>
              How we bring your vision to life.
            </Heading>
            <Grid
              gridGap={"30px"}
              gridTemplateColumns={"repeat(3, 1fr)"}
              mt={"40px"}
            >
              <GridItem colSpan={2}>
                <Box
                  bg={"gray"}
                  bgImage={ImagesList.about.services[0]}
                  borderRadius={"10px"}
                  height={"542px"}
                ></Box>
              </GridItem>
              <GridItem>
                <Box
                  bg={"gray"}
                  bgImage={ImagesList.about.services[1]}
                  borderRadius={"10px"}
                  height={"542px"}
                ></Box>
              </GridItem>
              <GridItem>
                <Box
                  bg={"gray"}
                  bgImage={ImagesList.about.services[2]}
                  borderRadius={"10px"}
                  height={"542px"}
                ></Box>
              </GridItem>
              <GridItem colSpan={2}>
                <Box
                  bg={"gray"}
                  bgImage={ImagesList.about.services[3]}
                  borderRadius={"10px"}
                  height={"542px"}
                ></Box>
              </GridItem>
            </Grid>
          </Box>
        </section>
      </main>
      <footer style={{ backgroundColor: "#002E3B" }}>
        <Box className="section-container" pt={"80px"} pb={"96px"} w="100%">
          <Heading
            textAlign={"center"}
            color={"secondary"}
            fontSize={"56px"}
            lineHeight={"100%"}
            letterSpacing={"-2.24px"}
          >
            Stay informed of
            <br /> our developments
          </Heading>
          <Box maxW={"492px"} mx={"auto"} mt={"59px"}>
            <Input
              borderColor={"white"}
              color={"white"}
              variant={"flushed"}
              placeholder="add your email"
              textAlign={"center"}
              fontSize={"32px"}
              fontWeight={400}
              fontFamily={"body"}
              pb={"22px"}
              h={"54px"}
            />
            <Box mx={"auto"} w="fit-content" mt={"44px"}>
              <Button
                label="Join our mailing list"
                border={"1px solid"}
                borderColor={"secondary"}
                _hover={{ color: "white", bgColor: "secondary" }}
                color={"secondary"}
                bg={"none"}
                transition={"background .5s linear"}
              />
            </Box>
          </Box>
          <Box pt={"76px"}>
            <Box
              w="100%"
              pb={"17.1px"}
              borderBottom={"1px solid rgba(225, 225, 225, 0.1)"}
            >
              <Image
                src={"/brand-logo-colored.svg"}
                alt="brand-logo"
                width={128}
                height={48.8}
              />
            </Box>
            <Flex color={"white"} mt={"15px"} justify={"space-between"}>
              <Stack spacing={"16px"} fontSize={"18px"}>
                <Text>
                  17 Emma Abimbola Cole Street,
                  <br /> Lekki Scheme 1, Lagos – Nigeria.{" "}
                </Text>
                <Text>+(234) 081-2268-7371</Text>
                <Text>info@firstsynergihomes.com</Text>
              </Stack>
              <Flex gap={"40px"} fontSize={"18px"} fontWeight={600}>
                <Text>Projects</Text>
                <Text>About us</Text>
                <Text>Blog</Text>
              </Flex>
            </Flex>
            <Flex mt={"54px"} justify={"space-between"}>
              <Flex color={"white"} fontSize={"18px"} gap={"40px"}>
                <Text>Terms & Conditions</Text>
                <Text>Privacy Policy</Text>
              </Flex>
              <Image
                src={"/socials.svg"}
                alt="brand-logo"
                width={133}
                height={22}
              />
            </Flex>
          </Box>
        </Box>
      </footer>
    </>
  );
}
