import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Flex,
  Grid,
  Heading,
  Input,
  SimpleGrid,
  Stack,
  Text,
} from "@chakra-ui/react";
import Navbar from "@/components/Navbar";
import Button from "@/components/Button";
import { ArrowForwardIcon } from "@chakra-ui/icons";
import { useEffect, useRef } from "react";
import { motion, useInView } from "framer-motion";
import HomeProjectCmp from "@/components/HomeProjectCmp";
import BlogItemCmp from "@/components/BlogItemCmp";
import ImageList from "@/images.json";

export default function Home() {
  const navRef = useRef(null);
  const isInView = useInView(navRef, { once: false, amount: 0.8 });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className="section-container">
          <Box
            position={"absolute"}
            top={"40px"}
            w="full"
            left={0}
            px={"100px"}
            mx={"auto"}
            zIndex={2}
          >
            <Navbar />
          </Box>
          <Box
            position={"fixed"}
            top={"40px"}
            w="full"
            left={0}
            px={"100px"}
            mx={"auto"}
            zIndex={2}
          >
            <Box
              display={isInView ? "none" : "block"}
              opacity={isInView ? 0 : 1}
              transition={"opacity .5s ease-in-out"}
              bg={"white"}
              boxShadow={"2px 2px 8px 0px rgba(0, 0, 0, 0.08)"}
              p="20px"
              borderRadius={"8px"}
            >
              <Navbar />
            </Box>
          </Box>
        </nav>
        <section ref={navRef}>
          <Box
            bgImage={"/hero-bg.png"}
            height={"900px"}
            bgPosition={"center"}
            bgSize={"cover"}
          >
            <Box color={"primary"} className="section-container" pt={"206px"}>
              <Heading
                fontSize={"92px"}
                fontWeight={700}
                lineHeight={"90px"}
                letterSpacing={"-3.68px"}
                maxW={"889px"}
              >
                Building <span style={{ color: "#C0972D" }}>exceptional</span>{" "}
                homes and a lifestyle of opulence.
              </Heading>
            </Box>
          </Box>
        </section>
        <section className="section-container">
          <Box py={"108px"}>
            <Flex justify={"space-between"}>
              <Box w="55%" maxW={"655px"}>
                <Text
                  fontSize={"20px"}
                  fontWeight={600}
                  letterSpacing={"4px"}
                  textTransform={"uppercase"}
                  color={"secondary"}
                >
                  our goal
                </Text>
                <Heading
                  color={"primary"}
                  fontSize={"56px"}
                  fontWeight={700}
                  lineHeight={"100%"}
                  letterSpacing={"-1.12px"}
                  my={"21px"}
                >
                  Building for maximum results
                </Heading>
                <Text
                  color={"primary"}
                  fontSize={"20px"}
                  fontWeight={400}
                  lineHeight={"130%"}
                >
                  First Synergi Homes is a captivating capsule of innovation,
                  energy, and symbiosis with its surroundings.
                </Text>
              </Box>
              <Box color={"primary"} w="45%" textAlign={"right"}>
                <Heading fontSize={"64px"} fontWeight={400} mb={0}>
                  100+
                </Heading>
                <Text fontSize={"30px"} fontWeight={700} lineHeight={"100%"}>
                  Homes
                </Text>
                <Heading fontSize={"64px"} fontWeight={400} mt="40px">
                  15+
                </Heading>
                <Text fontSize={"30px"} fontWeight={700} lineHeight={"100%"}>
                  Years of excellence
                </Text>
              </Box>
            </Flex>
            <Flex
              color={"secondary"}
              alignItems={"center"}
              gap={"4px"}
              mt={"50px"}
            >
              <Text>About First Synergi homes</Text>
              <ArrowForwardIcon />
            </Flex>
            <Box
              borderRadius={"10px"}
              h={"675px"}
              w="full"
              bg={"gray"}
              mt={"86px"}
            ></Box>
          </Box>
        </section>
        <section style={{ backgroundColor: "#002E3B" }}>
          <Box className="section-container" color={"white"} py={"98px"}>
            <Text
              fontSize={"20px"}
              fontWeight={600}
              letterSpacing={"4px"}
              color={"secondary"}
              textTransform={"uppercase"}
            >
              Projects
            </Text>
            <Flex
              alignItems={"flex-start"}
              mt={"21px"}
              justify={"space-between"}
            >
              <Stack spacing={"21px"} maxW={"665px"}>
                <Heading fontSize={"56px"} letterSpacing={"-2.24px"}>
                  Developing with the future in mind
                </Heading>
                <Text fontSize={"20px"} fontWeight={400} lineHeight={"130%"}>
                  We bring beautiful homes to market 3x faster.
                </Text>
              </Stack>
              <Flex alignItems={"center"} color={"secondary"} gap={"4px"}>
                <Text fontSize={"20px"} fontWeight={600}>
                  View featured projects
                </Text>
                <ArrowForwardIcon />
              </Flex>
            </Flex>
            <Flex
              className="no-scrollbar"
              gap={"64px"}
              mt={"102px"}
              position={"relative"}
              overflow={"scroll"}
            >
              {ImageList.home.projects.map((obj, index) => (
                <HomeProjectCmp key={index} data={obj} />
              ))}
            </Flex>
            <Box textAlign={"center"}>
              <Heading
                color={"secondary"}
                fontSize={"56px"}
                letterSpacing={"-2.24px"}
              >
                We are trusted
              </Heading>
              <Text
                fontSize={"20px"}
                fontWeight={400}
                lineHeight={"130%"}
                mt={"16px"}
              >
                Since inception we’ve been working with amazing clients to
                create meaningful
                <br /> impact and compelling experiences
              </Text>
            </Box>
          </Box>
        </section>
        <section className="section-container">
          <Box py={"96px"}>
            <Flex
              color={"primary"}
              alignItems={"flex-start"}
              justify={"space-between"}
            >
              <Box>
                <Heading fontSize={"56px"} letterSpacing={"-2.24px"}>
                  First insights
                </Heading>
                <Text fontSize={"20px"} lineHeight={"130%"} mt={"16px"}>
                  Stay informed with our latest insights
                </Text>
              </Box>
              <Flex alignItems={"center"} gap={"4px"}>
                <Text>View all</Text>
                <ArrowForwardIcon />
              </Flex>
            </Flex>
            <Grid
              gridGap={"20px"}
              mt={"48px"}
              gridTemplateColumns={{
                xl: "repeat(3, 1fr)",
                lg: "repeat(2, 1fr)",
              }}
            >
              <BlogItemCmp />
              <BlogItemCmp />
              <BlogItemCmp />
              <BlogItemCmp />
            </Grid>
          </Box>
        </section>
      </main>
      <footer style={{ backgroundColor: "#002E3B" }}>
        <Box className="section-container" pt={"80px"} pb={"96px"} w="100%">
          <Heading
            textAlign={"center"}
            color={"secondary"}
            fontSize={"56px"}
            lineHeight={"100%"}
            letterSpacing={"-2.24px"}
          >
            Stay informed of
            <br /> our developments
          </Heading>
          <Box maxW={"492px"} mx={"auto"} mt={"59px"}>
            <Input
              borderColor={"white"}
              color={"white"}
              variant={"flushed"}
              placeholder="add your email"
              textAlign={"center"}
              fontSize={"32px"}
              fontWeight={400}
              fontFamily={"body"}
              pb={"22px"}
              h={"54px"}
            />
            <Box mx={"auto"} w="fit-content" mt={"44px"}>
              <Button
                label="Join our mailing list"
                border={"1px solid"}
                borderColor={"secondary"}
                _hover={{ color: "white", bgColor: "secondary" }}
                color={"secondary"}
                bg={"none"}
                transition={"background .5s linear"}
              />
            </Box>
          </Box>
          <Box pt={"76px"}>
            <Box
              w="100%"
              pb={"17.1px"}
              borderBottom={"1px solid rgba(225, 225, 225, 0.1)"}
            >
              <Image
                src={"/brand-logo-colored.svg"}
                alt="brand-logo"
                width={128}
                height={48.8}
              />
            </Box>
            <Flex color={"white"} mt={"15px"} justify={"space-between"}>
              <Stack spacing={"16px"} fontSize={"18px"}>
                <Text>
                  17 Emma Abimbola Cole Street,
                  <br /> Lekki Scheme 1, Lagos – Nigeria.{" "}
                </Text>
                <Text>+(234) 081-2268-7371</Text>
                <Text>info@firstsynergihomes.com</Text>
              </Stack>
              <Flex gap={"40px"} fontSize={"18px"} fontWeight={600}>
                <Text>Projects</Text>
                <Text>About us</Text>
                <Text>Blog</Text>
              </Flex>
            </Flex>
            <Flex mt={"54px"} justify={"space-between"}>
              <Flex color={"white"} fontSize={"18px"} gap={"40px"}>
                <Text>Terms & Conditions</Text>
                <Text>Privacy Policy</Text>
              </Flex>
              <Image
                src={"/socials.svg"}
                alt="brand-logo"
                width={133}
                height={22}
              />
            </Flex>
          </Box>
        </Box>
      </footer>
    </>
  );
}
