import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Flex,
  Grid,
  GridItem,
  Heading,
  Input,
  SimpleGrid,
  Stack,
  Text,
} from "@chakra-ui/react";
import Navbar from "@/components/Navbar";
import Button from "@/components/Button";
import { ArrowForwardIcon } from "@chakra-ui/icons";
import { useEffect, useRef } from "react";
import { motion, useInView } from "framer-motion";
import HomeProjectCmp from "@/components/HomeProjectCmp";
import BlogItemCmp from "@/components/BlogItemCmp";
import FooterCmp from "@/components/FooterCmp";

export default function Projects() {
  const navRef = useRef(null);
  const isInView = useInView(navRef, { once: false, amount: 0.8 });
  console.log(isInView);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className="section-container">
          <Box
            display={{ lg: "block", base: "none" }}
            position={"absolute"}
            top={"40px"}
            w="full"
            left={0}
            px={"100px"}
            mx={"auto"}
            zIndex={2}
          >
            <Navbar />
          </Box>
          <Box
            display={{ lg: "block", base: "none" }}
            position={"fixed"}
            top={"40px"}
            w="full"
            left={0}
            px={"100px"}
            mx={"auto"}
            zIndex={2}
          >
            <Box
              display={isInView ? "none" : "block"}
              opacity={isInView ? 0 : 1}
              transition={"opacity .5s ease-in-out"}
              bg={"white"}
              boxShadow={"2px 2px 8px 0px rgba(0, 0, 0, 0.08)"}
              p="20px"
              borderRadius={"8px"}
            >
              <Navbar />
            </Box>
          </Box>
          <Box
            display={{ lg: "none", base: "block" }}
            position={"fixed"}
            top={"24px"}
            w="full"
            left={0}
            px={"16px"}
            zIndex={3}
          >
            <Box
              bg={"rgba(255, 255, 255, 0.80)"}
              boxShadow={"0px 12px 24px 6px rgba(153, 167, 177, 0.12)"}
              p="13px"
              borderRadius={"8px"}
            >
              <Navbar />
            </Box>
          </Box>
        </nav>
        <section ref={navRef}>
          <Box className="section-container" pt={"206px"}>
            <Heading
              fontSize={"72px"}
              fontWeight={700}
              lineHeight={"100%"}
              letterSpacing={"-2.88px"}
            >
              We build with you in mind;
              <br /> Innovative and excellent living
            </Heading>
          </Box>
          <Box h="444px" bg={"gray"} mt="62px"></Box>
        </section>
        <section className="section-container">
          <Box pt={"100px"} pb={"108px"}>
            <Box w="55%" maxW={"655px"}>
              <Text
                fontSize={"20px"}
                fontWeight={600}
                letterSpacing={"4px"}
                textTransform={"uppercase"}
                color={"primary"}
              >
                Featured projects
              </Text>
              <Heading
                color={"primary"}
                fontSize={"56px"}
                fontWeight={700}
                lineHeight={"100%"}
                letterSpacing={"-2.24px"}
                mt={"21px"}
              >
                Excellence and comfort is what we build for you
              </Heading>
            </Box>
            <Grid
              gridGap={"30px"}
              gridTemplateColumns={"repeat(3, 1fr)"}
              mt={"40px"}
            >
              <GridItem colSpan={2}>
                <Box bg={"gray"} borderRadius={"10px"} height={"542px"}></Box>
              </GridItem>
              <GridItem>
                <Box bg={"gray"} borderRadius={"10px"} height={"542px"}></Box>
              </GridItem>
              <GridItem>
                <Box bg={"gray"} borderRadius={"10px"} height={"542px"}></Box>
              </GridItem>
              <GridItem colSpan={2}>
                <Box bg={"gray"} borderRadius={"10px"} height={"542px"}></Box>
              </GridItem>
            </Grid>
          </Box>
        </section>
        <section>
          <Box color={"primary"} className="section-container">
            <Text
              fontSize={"20px"}
              fontWeight={600}
              letterSpacing={"4px"}
              textTransform={"uppercase"}
            >
              ongoing projects
            </Text>

            <Heading fontSize={"56px"} letterSpacing={"-2.24px"} mt="21px">
              We never stop building
              <br /> communities
            </Heading>

            <Flex
              className="no-scrollbar"
              gap={"64px"}
              mt={"40px"}
              position={"relative"}
              overflow={"scroll"}
            >
              <HomeProjectCmp other />
              <HomeProjectCmp other />
              <HomeProjectCmp other />
            </Flex>
            {/* <Box textAlign={"center"}>
              <Heading
                color={"secondary"}
                fontSize={"56px"}
                letterSpacing={"-2.24px"}
              >
                We are trusted
              </Heading>
              <Text
                fontSize={"20px"}
                fontWeight={400}
                lineHeight={"130%"}
                mt={"16px"}
              >
                Since inception we’ve been working with amazing clients to
                create meaningful
                <br /> impact and compelling experiences
              </Text>
            </Box> */}
          </Box>
        </section>
        <section className="section-container">
          <Box pb={"100px"}>
            <Box>
              <Text
                fontSize={"20px"}
                fontWeight={600}
                letterSpacing={"4px"}
                textTransform={"uppercase"}
              >
                More projects
              </Text>
              <Heading fontSize={"56px"} letterSpacing={"-2.24px"} mt={"21px"}>
                See First Synergi Projects
              </Heading>
            </Box>

            <Grid
              gridGap={"20px"}
              mt={"48px"}
              gridTemplateColumns={{
                xl: "repeat(3, 1fr)",
                lg: "repeat(3, 1fr)",
              }}
            >
              <GridItem colSpan={2}>
                <Box bg={"gray"} borderRadius={"10px"} height={"542px"}></Box>
              </GridItem>
              <GridItem>
                <Box bg={"gray"} borderRadius={"10px"} height={"542px"}></Box>
              </GridItem>
            </Grid>
            <Box mx={"auto"} w="fit-content">
              <Button mt={"63px"} label="Load more" />
            </Box>
          </Box>
        </section>
      </main>
      <FooterCmp />
    </>
  );
}
