import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Flex,
  Grid,
  GridItem,
  Heading,
  Input,
  SimpleGrid,
  Stack,
  Text,
} from "@chakra-ui/react";
import Navbar from "@/components/Navbar";
import Button from "@/components/Button";
import { ArrowForwardIcon } from "@chakra-ui/icons";
import { useEffect, useRef, useState } from "react";
import { motion, useInView } from "framer-motion";
import HomeProjectCmp from "@/components/HomeProjectCmp";
import BlogItemCmp from "@/components/BlogItemCmp";
import ImagesList from "@/images.json";
import FooterCmp from "@/components/FooterCmp";
import { TypeAnimation } from "react-type-animation";
import SectionAnimation from "@/components/SectionAnimation";

export default function Projects() {
  const navRef = useRef(null);
  const isInView = useInView(navRef, { once: false, amount: 0.6 });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className="section-container">
          <Box
            display={{ lg: "block", base: "none" }}
            position={"absolute"}
            top={"40px"}
            w="full"
            left={0}
            px={"100px"}
            mx={"auto"}
            zIndex={2}
          >
            <Navbar />
          </Box>
          <Box
            display={{ lg: "block", base: "none" }}
            position={"fixed"}
            top={"40px"}
            w="full"
            left={0}
            px={"100px"}
            mx={"auto"}
            zIndex={2}
          >
            <Box
              display={isInView ? "none" : "block"}
              opacity={isInView ? 0 : 1}
              transition={"opacity .5s ease-in-out"}
              bg={"white"}
              boxShadow={"2px 2px 8px 0px rgba(0, 0, 0, 0.08)"}
              p="20px"
              borderRadius={"8px"}
            >
              <Navbar />
            </Box>
          </Box>
          <Box
            display={{ lg: "none", base: "block" }}
            position={"fixed"}
            top={"24px"}
            w="full"
            left={0}
            px={"16px"}
            zIndex={3}
          >
            <Box
              bg={"rgba(255, 255, 255, 0.98)"}
              boxShadow={"0px 12px 24px 6px rgba(153, 167, 177, 0.12)"}
              p="13px"
              borderRadius={"8px"}
            >
              <Navbar />
            </Box>
          </Box>
        </nav>
        <section ref={navRef}>
          <Box
            className="section-container"
            pt={{ lg: "206px", base: "180px" }}
            height={{ lg: "400px", base: "300px" }}
          >
            <TypeAnimation
              sequence={[
                "We build with you in mind; Innovative and excellent living.",
                1000,
              ]}
              speed={10}
              style={{ color: "#002E3B" }}
              wrapper="h2"
              className="heading-2"
              repeat={1}
              cursor={false}
            />
          </Box>
          <Box
            h={{ lg: "444px", base: "236px" }}
            bg={"gray"}
            bgImage={ImagesList.projects.hero}
            bgSize={"cover"}
            bgRepeat={"no-repeat"}
            bgPosition={"center"}
            mt={{ lg: "62px", base: "32px" }}
          />
        </section>
        <section className="section-container">
          <SectionAnimation>
            <Box pt={"100px"} pb={"108px"}>
              <Box w={{ lg: "55%", base: "full" }} maxW={"655px"}>
                <Text className="body-text-1" color={"secondary"}>
                  Featured projects
                </Text>
                <Heading color={"primary"} className="heading-3" mt={"21px"}>
                  Excellence and comfort is what we build for you
                </Heading>
              </Box>
              <Grid
                gridGap={"30px"}
                gridTemplateColumns={{
                  lg: "repeat(3, 1fr)",
                  base: "repeat(1, 1fr)",
                }}
                mt={"40px"}
              >
                <GridItem colSpan={2}>
                  <Box
                    bg={"gray"}
                    bgImage={ImagesList.projects.project_images[0]}
                    borderRadius={"10px"}
                    height={"542px"}
                  ></Box>
                </GridItem>
                <GridItem>
                  <Box
                    bg={"gray"}
                    bgImage={ImagesList.projects.project_images[1]}
                    borderRadius={"10px"}
                    height={"542px"}
                  ></Box>
                </GridItem>
                <GridItem>
                  <Box
                    bg={"gray"}
                    bgImage={ImagesList.projects.project_images[2]}
                    borderRadius={"10px"}
                    height={"542px"}
                  ></Box>
                </GridItem>
                <GridItem colSpan={2}>
                  <Box
                    bg={"gray"}
                    bgImage={ImagesList.projects.project_images[3]}
                    borderRadius={"10px"}
                    height={"542px"}
                  ></Box>
                </GridItem>
              </Grid>
            </Box>
          </SectionAnimation>
        </section>
        <section>
          <SectionAnimation>
            <Box color={"primary"} className="section-container">
              <Text className="body-text-1" color={"secondary"}>
                ongoing projects
              </Text>

              <Heading className="heading-3" mt="21px">
                We never stop building
                <br /> communities
              </Heading>

              <Flex
                className="no-scrollbar"
                gap={"64px"}
                mt={"40px"}
                position={"relative"}
                overflow={"scroll"}
              >
                <HomeProjectCmp other />
                <HomeProjectCmp other />
                <HomeProjectCmp other />
              </Flex>
            </Box>
          </SectionAnimation>
        </section>
        <section className="section-container">
          <SectionAnimation>
            <Box pb={"100px"}>
              <Box>
                <Text
                  fontSize={"20px"}
                  fontWeight={600}
                  letterSpacing={"4px"}
                  textTransform={"uppercase"}
                >
                  More projects
                </Text>
                <Heading
                  fontSize={"56px"}
                  letterSpacing={"-2.24px"}
                  mt={"21px"}
                >
                  See First Synergi Projects
                </Heading>
              </Box>

              <Grid
                gridGap={"20px"}
                mt={"48px"}
                gridTemplateColumns={{
                  xl: "repeat(3, 1fr)",
                  lg: "repeat(3, 1fr)",
                }}
              >
                <GridItem colSpan={2}>
                  <Box bg={"gray"} borderRadius={"10px"} height={"542px"}></Box>
                </GridItem>
                <GridItem>
                  <Box bg={"gray"} borderRadius={"10px"} height={"542px"}></Box>
                </GridItem>
              </Grid>
              <Box mx={"auto"} w="fit-content">
                <Button mt={"63px"} label="Load more" />
              </Box>
            </Box>
          </SectionAnimation>
        </section>
      </main>
      <FooterCmp />
    </>
  );
}
