import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Flex,
  Grid,
  GridItem,
  Heading,
  Input,
  SimpleGrid,
  Stack,
  Text,
} from "@chakra-ui/react";
import Navbar from "@/components/Navbar";
import Button from "@/components/Button";
import { ArrowForwardIcon } from "@chakra-ui/icons";
import { useEffect, useRef } from "react";
import { motion, useInView } from "framer-motion";
import HomeProjectCmp from "@/components/HomeProjectCmp";
import BlogItemCmp from "@/components/BlogItemCmp";
import ImagesList from "@/images.json";

export default function Projects() {
  const navRef = useRef(null);
  const isInView = useInView(navRef, { once: false, amount: 0.6 });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <nav className="section-container">
          <Box
            position={"absolute"}
            top={"40px"}
            w="full"
            left={0}
            px={"100px"}
            mx={"auto"}
            zIndex={2}
          >
            <Navbar />
          </Box>
          <Box
            position={"fixed"}
            top={"40px"}
            w="full"
            left={0}
            px={"100px"}
            mx={"auto"}
            zIndex={2}
          >
            <Box
              display={isInView ? "none" : "block"}
              // opacity={isInView ? 0 : 1}
              transition={"opacity .5s ease-in-out"}
              bg={"white"}
              boxShadow={"2px 2px 8px 0px rgba(0, 0, 0, 0.08)"}
              p="20px"
              borderRadius={"8px"}
            >
              <Navbar />
            </Box>
          </Box>
        </nav>
        <section ref={navRef}>
          <Box className="section-container" pt={"206px"}>
            <Heading
              color={"primary"}
              fontSize={"72px"}
              fontWeight={700}
              lineHeight={"100%"}
              letterSpacing={"-2.88px"}
            >
              We build with you in mind;
              <br /> Innovative and excellent living
            </Heading>
          </Box>
          <Box
            h="444px"
            bg={"gray"}
            bgImage={ImagesList.projects.hero}
            bgSize={"cover"}
            bgRepeat={"no-repeat"}
            bgPosition={"center"}
            mt="62px"
          />
        </section>
        <section className="section-container">
          <Box pt={"100px"} pb={"108px"}>
            <Box w="55%" maxW={"655px"}>
              <Text
                fontSize={"20px"}
                fontWeight={600}
                letterSpacing={"4px"}
                textTransform={"uppercase"}
                color={"primary"}
              >
                Featured projects
              </Text>
              <Heading
                color={"primary"}
                fontSize={"56px"}
                fontWeight={700}
                lineHeight={"100%"}
                letterSpacing={"-2.24px"}
                mt={"21px"}
              >
                Excellence and comfort is what we build for you
              </Heading>
            </Box>
            <Grid
              gridGap={"30px"}
              gridTemplateColumns={"repeat(3, 1fr)"}
              mt={"40px"}
            >
              <GridItem colSpan={2}>
                <Box
                  bg={"gray"}
                  bgImage={ImagesList.projects.project_images[0]}
                  borderRadius={"10px"}
                  height={"542px"}
                ></Box>
              </GridItem>
              <GridItem>
                <Box
                  bg={"gray"}
                  bgImage={ImagesList.projects.project_images[1]}
                  borderRadius={"10px"}
                  height={"542px"}
                ></Box>
              </GridItem>
              <GridItem>
                <Box
                  bg={"gray"}
                  bgImage={ImagesList.projects.project_images[2]}
                  borderRadius={"10px"}
                  height={"542px"}
                ></Box>
              </GridItem>
              <GridItem colSpan={2}>
                <Box
                  bg={"gray"}
                  bgImage={ImagesList.projects.project_images[3]}
                  borderRadius={"10px"}
                  height={"542px"}
                ></Box>
              </GridItem>
            </Grid>
          </Box>
        </section>
        <section>
          <Box color={"primary"} className="section-container">
            <Text
              fontSize={"20px"}
              fontWeight={600}
              letterSpacing={"4px"}
              textTransform={"uppercase"}
            >
              ongoing projects
            </Text>

            <Heading fontSize={"56px"} letterSpacing={"-2.24px"} mt="21px">
              We never stop building
              <br /> communities
            </Heading>

            <Flex
              className="no-scrollbar"
              gap={"64px"}
              mt={"40px"}
              position={"relative"}
              overflow={"scroll"}
            >
              <HomeProjectCmp other />
              <HomeProjectCmp other />
              <HomeProjectCmp other />
            </Flex>
          </Box>
        </section>
        <section className="section-container">
          <Box pb={"100px"}>
            <Box>
              <Text
                fontSize={"20px"}
                fontWeight={600}
                letterSpacing={"4px"}
                textTransform={"uppercase"}
              >
                More projects
              </Text>
              <Heading fontSize={"56px"} letterSpacing={"-2.24px"} mt={"21px"}>
                See First Synergi Projects
              </Heading>
            </Box>

            <Grid
              gridGap={"20px"}
              mt={"48px"}
              gridTemplateColumns={{
                xl: "repeat(3, 1fr)",
                lg: "repeat(3, 1fr)",
              }}
            >
              <GridItem colSpan={2}>
                <Box bg={"gray"} borderRadius={"10px"} height={"542px"}></Box>
              </GridItem>
              <GridItem>
                <Box bg={"gray"} borderRadius={"10px"} height={"542px"}></Box>
              </GridItem>
            </Grid>
            <Box mx={"auto"} w="fit-content">
              <Button mt={"63px"} label="Load more" />
            </Box>
          </Box>
        </section>
      </main>
      <footer style={{ backgroundColor: "#002E3B" }}>
        <Box className="section-container" pt={"80px"} pb={"96px"} w="100%">
          <Heading
            textAlign={"center"}
            color={"secondary"}
            fontSize={"56px"}
            lineHeight={"100%"}
            letterSpacing={"-2.24px"}
          >
            Stay informed of
            <br /> our developments
          </Heading>
          <Box maxW={"492px"} mx={"auto"} mt={"59px"}>
            <Input
              borderColor={"white"}
              color={"white"}
              variant={"flushed"}
              placeholder="add your email"
              textAlign={"center"}
              fontSize={"32px"}
              fontWeight={400}
              fontFamily={"body"}
              pb={"22px"}
              h={"54px"}
            />
            <Box mx={"auto"} w="fit-content" mt={"44px"}>
              <Button
                label="Join our mailing list"
                border={"1px solid"}
                borderColor={"secondary"}
                _hover={{ color: "white", bgColor: "secondary" }}
                color={"secondary"}
                bg={"none"}
                transition={"background .5s linear"}
              />
            </Box>
          </Box>
          <Box pt={"76px"}>
            <Box
              w="100%"
              pb={"17.1px"}
              borderBottom={"1px solid rgba(225, 225, 225, 0.1)"}
            >
              <Image
                src={"/brand-logo-colored.svg"}
                alt="brand-logo"
                width={128}
                height={48.8}
              />
            </Box>
            <Flex color={"white"} mt={"15px"} justify={"space-between"}>
              <Stack spacing={"16px"} fontSize={"18px"}>
                <Text>
                  17 Emma Abimbola Cole Street,
                  <br /> Lekki Scheme 1, Lagos – Nigeria.{" "}
                </Text>
                <Text>+(234) 081-2268-7371</Text>
                <Text>info@firstsynergihomes.com</Text>
              </Stack>
              <Flex gap={"40px"} fontSize={"18px"} fontWeight={600}>
                <Text>Projects</Text>
                <Text>About us</Text>
                <Text>Blog</Text>
              </Flex>
            </Flex>
            <Flex mt={"54px"} justify={"space-between"}>
              <Flex color={"white"} fontSize={"18px"} gap={"40px"}>
                <Text>Terms & Conditions</Text>
                <Text>Privacy Policy</Text>
              </Flex>
              <Image
                src={"/socials.svg"}
                alt="brand-logo"
                width={133}
                height={22}
              />
            </Flex>
          </Box>
        </Box>
      </footer>
    </>
  );
}
